### ISSUE TITLE
ModuleNotFoundError: No module named 'mateco.ipa'

### ISSUE THREAD

**Issue by KhaledAnaqwa** [tquangsdh20/mateco#1]
from .ipa import _IPA
ModuleNotFoundError: No module named 'mateco.ipa'

on Mac OS

**Comment by tquangsdh20** [comment]
I'm sorry to say that this library is not support for all Python Version. If you need to convert text to speech maybe I'll try to fix this library soon for all python versions as well as all operation systems. If you wanna convert text to IPA, you can find out the library text2ipa support for all operation systems with Python version >= 3.6.  Github: https://github.com/tquangsdh20/text2ipa

**Comment by tquangsdh20** [comment]
Hello KhaledAnaqwa,
The issue has been fixed. I have tested for the macOS in GitLab.
I hope it works for you. 
Please check it one more time and give me your feedback.
